name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  initial-setup-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Check project structure
        run: |
          echo "=== Project Structure ==="
          ls -la
          echo "=== Mobile Directory ==="
          ls -la mobile/ || echo "Mobile directory not found"
          echo "=== Backend Directory ==="
          ls -la backend/ || echo "Backend directory not found"
          echo "=== Shared Directory ==="
          ls -la shared/ || echo "Shared directory not found"

      - name: Run linting (if available)
        run: npm run lint --if-present || echo "No lint script found"

      - name: Run tests (if available)
        run: npm test --if-present || echo "No test script found"

      - name: Check TypeScript compilation
        run: |
          if [ -f "mobile/tsconfig.json" ]; then
            cd mobile
            npx tsc --noEmit --skipLibCheck || echo "TypeScript check failed, continuing..."
          else
            echo "No TypeScript config found in mobile directory"
          fi
